{% set name = "cachelib" %}
{% set version = "0.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cachelib-{{ version }}.tar.gz
  sha256: 38222cc7c1b79a23606de5c2607f4925779e37cdcea1c2ad21b8bae94b5425a5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7

test:
  imports:
    - cachelib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pallets-eco/cachelib
  summary: A collection of cache libraries in the same API interface.
  license: BSD-3-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - fuglede
