{% set name = "cachelib" %}
{% set version = "0.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 73fedcadd0ba818fb2bb9f3c7cd5fcc2a71e86286f1842f55f28d500faee17f1

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<38]

requirements:
  host:
    - pip
    - setuptools
    - python
    - flit-core <4
  run:
    - python

# pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 61] Connection refused
{% set ignore_tests = " --ignore=tests/test_dynamodb_cache.py" %}
{% set ignore_tests = ignore_tests + " --ignore=tests/test_mongodb_cache.py" %}

test:
  source_files:
    - tests
  imports:
    - cachelib
    - cachelib.base
    - cachelib.dynamodb
    - cachelib.file
    - cachelib.memcached
    - cachelib.mongodb
    - cachelib.redis
    - cachelib.serializers
    - cachelib.simple
    - cachelib.uwsgi
  requires:
    - pip
    - pytest >=8.0.0
    - pytest-xprocess >=0.23.0
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v tests {{ ignore_tests }}

about:
  home: https://github.com/pallets-eco/cachelib
  summary: A collection of cache libraries in the same API interface. Extracted from Werkzeug.
  description: A collection of cache libraries in the same API interface. Extracted from Werkzeug.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  doc_url: https://cachelib.readthedocs.io
  dev_url: https://github.com/pallets-eco/cachelib

extra:
  recipe-maintainers:
    - fuglede
