{% set name = "cachelib" %}
{% set version = "0.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cachelib-{{ version }}.tar.gz
  sha256: 1bfa8d7473509d4892241962d6b41ba1b55e64b6f57632478b29564e1f60ef8c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - cachelib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pallets/cachelib
  summary: A collection of cache libraries in the same API interface.
  license: BSD-3-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - fuglede
